# @host = http://localhost:3000
@host = https://api-wliayah.vercel.app

### get provincies
GET {{host}}/region/provinces

### get one province
@provinsi_id = 19
GET {{host}}/region/province/{{provinsi_id}}

### get regencies / cities
@provinsi_id = 19
GET {{host}}/region/regencies/{{provinsi_id}}

### get one regency / city
@kabupaten_id = 314
GET {{host}}/region/regency/{{kabupaten_id}}

### get districts
@kabupaten_id = 314
GET {{host}}/region/districts/{{kabupaten_id}}

### get one district
@kecamatan_id = 6362
GET {{host}}/region/district/{{kecamatan_id}}

### get kelurahan
@kecamatan_id = 6362
GET {{host}}/region/villages/{{kecamatan_id}}

### get one kelurahan
@kelurahan_id = 6362
GET {{host}}/region/village/{{kelurahan_id}}